[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bcs = "0.1.6"
sha2 = "0.10"
crmf = { path = "../../crmf" }
ark-bn254 = "0.4.0"
ark-ff = "0.4.0"
ark-ec = "0.4.0"
ark-crypto-primitives = { version = "0.4.0", features = ["sponge"] }

[features]
poseidon2 = []
